name: ftw_solucoes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.2+7
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.0
  dio: ^5.4.1
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  build_runner: ^2.4.8
  test: ^1.25.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/pix.png
    - assets/animations/


