name: ftw_solucoes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_app_check: ^0.2.2+7
  image_picker: ^1.0.5
  google_fonts: ^6.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.1.0
  dio: ^5.4.1
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.3.0
  flutter_masked_text2: ^0.9.0
  url_launcher: ^6.2.2
  timezone: ^0.10.1
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  flutter_dotenv: ^5.1.0
  uuid: ^4.2.1
  flutter_local_notifications: ^19.2.1
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.13.0
  build_runner: ^2.4.8
  test: ^1.25.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"


